# Generated by Django 6.0.1 on 2026-02-02 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='URL of the video to be analyzed', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the analysis was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the analysis was last updated')),
                ('title', models.CharField(blank=True, help_text='Title of the video', max_length=500, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration of the video in seconds', null=True)),
                ('language_code', models.CharField(blank=True, help_text="Language code of the video's audio", max_length=10, null=True)),
                ('transcript', models.TextField(blank=True, help_text="Transcription of the video's audio", null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Sentiment of the video content', max_length=10, null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Score representing the sentiment strength', null=True)),
                ('tone', models.CharField(blank=True, help_text='Tone of the video content', max_length=100, null=True)),
                ('key_points', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='The 3 key points of the video', size=3)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Errors encountered during processing', null=True)),
            ],
            options={
                'verbose_name': 'Video Analysis',
                'verbose_name_plural': 'Video Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
