# Generated by Django 6.0.1 on 2026-02-02 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='key_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='The 3 key points of the video', null=True, size=3),
        ),
    ]
